export const schemeDemo = [
  {
    name: "scheme",
    label: "scheme",
    required: true,
    type: "radio",
    dataType: "string",
    defaultVal: "https",
    value: "https",
    options: [
      {
        value: "http",
        label: "http",
      },
      {
        value: "https",
        label: "https",
      },
    ],
  },
  {
    name: "pos",
    label: "平台",
    required: true,
    type: "checkbox",
    dataType: "string",
    defaultVal: ["https"],
    value: ["https"],
    options: [
      {
        value: "http",
        label: "http",
      },
      {
        value: "https",
        label: "https",
      },
    ],
  },
  {
    name: "riqi",
    label: "日期",
    required: false,
    type: "date",
    dataType: "string",
    defaultVal: "",
    value: "",
  },
  {
    name: "num",
    label: "数字选择",
    required: false,
    type: "number",
    dataType: "number",
    defaultVal: null,
    value: null,
  },
  {
    name: "shijian",
    label: "时间",
    required: false,
    type: "time",
    dataType: "string",
    defaultVal: "",
    value: "",
  },
  {
    name: "riqishijian",
    label: "日期时间",
    required: false,
    type: "datetime",
    dataType: "string",
    defaultVal: "",
    value: "",
  },
  {
    name: "connectTimeout",
    label: "连接超时",
    required: false,
    type: "input",
    dataType: "number",
    defaultVal: "30000",
    value: "30000",
  },
  {
    name: "socketTimeout",
    label: "socket超时",
    required: false,
    type: "input",
    dataType: "number",
    defaultVal: "60000",
    value: "60000",
  },
  {
    name: "requestTimeout",
    label: "请求超时",
    required: false,
    type: "input",
    dataType: "number",
    defaultVal: "30000",
    value: "30000",
  },
  {
    name: "requestTimeout",
    label: "请求超时22",
    required: false,
    type: "input",
    dataType: "number",
    defaultVal: "",
    value: "",
  },
  {
    name: "credential",
    label: "身份验证",
    required: true,
    type: "select",
    dataType: "object",
    defaultVal: "2",
    value: null,
    options: [
      {
        value: "0",
        label: "None",
      },
      {
        value: "1",
        label: "API Key",
        fields: [
          {
            name: "apiKey",
            label: "API Key",
            required: true,
            type: "input",
            dataType: "string",
            defaultVal: null,
          },
        ],
      },
      {
        value: "2",
        label: "账号密码(CA证书)",
        fields: [
          {
            name: "username",
            label: "用户名",
            required: false,
            type: "input",
            dataType: "string",
            defaultVal: null,
            value: "222"
          },
          {
            name: "password",
            label: "密码",
            required: false,
            type: "password",
            dataType: "string",
            defaultVal: null,
            crypto: "rsa",
            value: "password111",
          },
          {
            name: "crtPath",
            label: "证书路径",
            required: false,
            type: "input",
            dataType: "string",
            defaultVal: null,
            value: null,
          },
        ],
      },
      {
        value: "3",
        label: "账号密码(指纹)",
        fields: [
          {
            name: "username",
            label: "用户名",
            required: false,
            type: "input",
            dataType: "string",
            defaultVal: null,
          },
          {
            name: "password",
            label: "密码",
            required: false,
            type: "password",
            dataType: "string",
            defaultVal: null,
            crypto: "rsa",
            value: "",
          },
          {
            name: "fingerprint",
            label: "指纹",
            required: false,
            type: "input",
            dataType: "string",
            defaultVal: null,
            value: null,
          },
        ],
      },
    ],
  },
  {
    name: "map",
    label: "map",
    required: true,
    type: "map",
    dataType: "string",
    defaultVal: [],
    value: [{ key: "name", value: "张三" }],
  },
];
